# Site settings
title: Hackerkid's Blog
email: yo@vishnuks.com
description: > # this means to ignore newlines until "baseurl:"
  This is the blog of Vishnu KS aka Hackerkid
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hackerkid.github.io" # the base hostname & protocol for your site
twitter_username: hackerkidx
github_username:  hackerkid

# Build settings
markdown: kramdown
