# Site not entirely customized using config
# Some meta tags in _includes/head.html and other file contents need manual edits
title: Srijan Agarwal
email: srijan@wikitolearn.org
author: Srijan Agarwal
description:  # this means to ignore newlines until "baseurl:"
  Web Developer, 19. I code, eat and write.
baseurl: ""
url: "https://srijancse.github.io"
twitter_username: srijancse
github_username: srijancse
linkedin_username: srijancse
facebook_username: srijancse
medium_username: srijancse
google_analytics: UA-83244237-1 # get yours at https://analytics.google.com/analytics/web/

html_lang: en
permalink: /writing/:title/
exclude: [".ruby-version", "Gemfile", "Gemfile.lock", "wercker.yml"]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-seo-tag
