# Site not entirely customized using config
# Some meta tags in _includes/head.html and other file contents need manual edits
title: Srijan Agarwal
email: srijan@wikitolearn.org
author: Srijan Agarwal
description:  # this means to ignore newlines until "baseurl:"
  Web Developer, 19. I code, eat and write.
baseurl: ""
url: "http://srijancse.github.io"
twitter_username: srijancse
github_username: srijancse
linkedin_username: srijancse
facebook_username: srijancse
medium_username: srijancse
google_analytics: UA-83244237-1 # get yours at http://analytics.google.com/analytics/web/

html_lang: en
permalink: /writing/:title/
exclude: [".ruby-version", "Gemfile", "Gemfile.lock", "wercker.yml"]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-seo-tag
tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag
tag_permalink_style: pretty
ignored_tags: [tags,to,ignore]
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: srijancse
