# Site settings
title: Srijan Agarwal's Blog
email: srijan@wikitolearn.org
description: > # this means to ignore newlines until "baseurl:"
  This is the blog of Srijan Agarwal
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://srijancse.github.io" # the base hostname & protocol for your site
twitter_username: srijancse
github_username:  srijancse

# Build settings
markdown: kramdown
